### ISSUE TITLE
How can download/upload with progress number?

### ISSUE THREAD

**Issue by nvnguyenit** [cuzv/CHXNetworkingWrapper#1]
Hi man,

Your library is so great. It save my time more. So, how can use this library to download/upload with progress number?

Thanks man

**Comment by cuzv** [comment]
Thanks for you like it. 
The bad news is it not support download/upload progress currently. :[
The god news is it will support soon. :]
Recently busy, I will add these features as soon as possible.

**Comment by nvnguyenit** [comment]
Thanks man, hope it support soon :D
