### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by nvnguyenit** [cuzv/CHXNetworkingWrapper#2]
Hi man!

In current version, Did you removed CHXResponseCache ? i don't understand about this. Can you explain more detail about this? Will we use another cache?

Best regard,

Nguyen

**Comment by cuzv** [comment]
Yep~

Former version use archive for cache request is not the right way for remain the request result. Better way should be use database for those works, which means will be complex, should combine what business you are deal with, not suitable for place in networking layer.

As [Mattt](https://github.com/mattt/) pointed out, networking request cache should be process by `NSURLCache`

> AFNetworking takes advantage of the caching functionality already provided by NSURLCache and any of its subclasses. So long as your NSURLRequest objects have the correct cache policy, and your server response contains a valid Cache-Control header, responses will be automatically cached for subsequent requests.

[checkout here](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-FAQ)

So, I just removed those wrong approach way code.

BTW, If you are using `Swift`, you may interested in [this swift version stuff.](https://github.com/cuzv/redes)
